---

- name: Install required apt packages (newer systems)
  apt:
    pkg: '{{ item }}'
  with_items:
    - gpg
    - apt-transport-https
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= '18.04')

- name: Install required apt packages (newer systems)
  apt:
    pkg: '{{ item }}'
  with_items:
    - gnupg
    - apt-transport-https
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int <= 8) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= '16.04')

- name: Install yarn key
  apt_key:
    url: '{{ yarn_apt_key }}'
    state: present

- name: Add yarn repositories
  apt_repository:
    repo: '{{ item }}'
    state: present
    filename: yarn
  with_items: '{{ yarn_repository_urls }}'

- name: Install yarn apt packages
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ yarn_apt_packages }}'
