---

- name: Install gpg (newer systems)
  apt:
    pkg: 'gpg'
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= '18.04')

- name: Install gpg (older systems)
  apt:
    pkg: 'gnupg'
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int <= 8) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= '16.04')

- name: Install required apt packages
  apt:
    pkg: 'apt-transport-https'
    cache_valid_time: 86400
    update_cache: yes

- name: Install yarn key
  apt_key:
    url: '{{ yarn_apt_key }}'
    state: present

- name: Add yarn repositories
  apt_repository:
    repo: '{{ item }}'
    state: present
    filename: yarn
  with_items: '{{ yarn_repository_urls }}'

- name: Install yarn apt packages
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ yarn_apt_packages }}'
